export enum BoardActionType {
  //   ===BOARD===
  UPDATE_BOARD_TITLE = "UPDATE_BOARD_TITLE",

  // ===LIST===
  ADD_LIST = "ADD_LIST",
  DELETE_LIST = "DELETE_LIST",
  UPDATE_LIST_TITLE = "UPDATE_LIST_TITLE",
  MOVE_LIST = "MOVE_LIST",

  //   ===CARD===
  ADD_CARD = "ADD_CARD",
  DELETE_CARD = "DELETE_CARD",
  UPDATE_CARD_TITLE = "DELETE_CARD",
  MOVE_CARD = "MOVE_CARD",

  //   ===COMMENT===
  ADD_COMMENT = "ADD_COMMENT",
}
